<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <IsPackable>false</IsPackable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <None Update="Assets\*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Triangles.BaseApp\Triangles.BaseApp.csproj" />
      <ProjectReference Include="..\..\Triangles.Core\Triangles.Core.csproj" />
      <ProjectReference Include="..\Triangles\Triangles.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Vortice.Dxc" Version="3.8.3" />
    </ItemGroup>

    <ItemGroup>
      <ClCompile Include="Assets\Triangle.hlsl" />
    </ItemGroup>

</Project>
