<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GLFW.NET.Natives" Version="1.0.1"/>
        <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.2" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
        <PackageReference Include="Vortice.D3DCompiler" Version="3.6.2"/>
        <PackageReference Include="Vortice.Direct2D1" Version="3.6.2" />
        <PackageReference Include="Vortice.Direct3D11" Version="3.6.2"/>
        <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
        <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Properties\Develop.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
